micronaut:
  application:
    name: semantic-web
  server:
      read-timeout: 60
  dbpedia:
    organization: micronaut
    repository: profiles
    apiversion: v1
  elasticsearch:
    httpHosts: "http://localhost:9200,http://127.0.0.2:9200"
