micronaut:
  application:
    name: semantic-web
  server:
      read-timeout: 60
      port: 8081
  dbpedia:
    organization: micronaut
    repository: profiles
    apiversion: v1
  neo4j:
    uri: bolt://localhost
  http:
      client:
          read-timeout: 300s

